package modelos;
// Generated 27-feb-2018 8:34:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer id;
     private Faccion faccion;
     private String nombre;
     private int cantidadPersonajes;
     private Set personajes = new HashSet(0);

    public Jugador() {
    }

	
    public Jugador(Faccion faccion, String nombre, int cantidadPersonajes) {
        this.faccion = faccion;
        this.nombre = nombre;
        this.cantidadPersonajes = cantidadPersonajes;
    }
    public Jugador(Faccion faccion, String nombre, int cantidadPersonajes, Set personajes) {
       this.faccion = faccion;
       this.nombre = nombre;
       this.cantidadPersonajes = cantidadPersonajes;
       this.personajes = personajes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Faccion getFaccion() {
        return this.faccion;
    }
    
    public void setFaccion(Faccion faccion) {
        this.faccion = faccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidadPersonajes() {
        return this.cantidadPersonajes;
    }
    
    public void setCantidadPersonajes(int cantidadPersonajes) {
        this.cantidadPersonajes = cantidadPersonajes;
    }
    public Set getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Set personajes) {
        this.personajes = personajes;
    }




}


