package modelo;
// Generated 04-mar-2018 12:45:47 by Hibernate Tools 4.3.1



/**
 * Personaje generated by hbm2java
 */
public class Personaje  implements java.io.Serializable {


     private Integer id;
     private Hermandad hermandad;
     private Jugador jugador;
     private String nombre;
     private int nivel;

    public Personaje() {
    }

    public Personaje(Hermandad hermandad, Jugador jugador, String nombre, int nivel) {
       this.hermandad = hermandad;
       this.jugador = jugador;
       this.nombre = nombre;
       this.nivel = nivel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hermandad getHermandad() {
        return this.hermandad;
    }
    
    public void setHermandad(Hermandad hermandad) {
        this.hermandad = hermandad;
    }
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }




}


